# Generated by Django 5.2.17 on 2026-09-19 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField(help_text='Analiz edilecek haber metni / iddia.')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('query', models.CharField(blank=True, help_text='Sosyal medya/haber aramasinda kullanilan sorgu.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('running', 'Calisiyor'), ('completed', 'Tamamlandi'), ('failed', 'Basarisiz')], default='pending', max_length=20)),
                ('nlp_result', models.JSONField(blank=True, help_text='nlp_engine tarafindan uretilen semantik/siniflandirma sonucu.', null=True)),
                ('gnn_result', models.JSONField(blank=True, help_text='graph_engine tarafindan uretilen yayilim grafigi analiz sonucu.', null=True)),
                ('bot_analysis_result', models.JSONField(blank=True, help_text='Bot/organize davranis tespiti sonucu (kullanici bazli skorlar).', null=True)),
                ('source_verification_result', models.JSONField(blank=True, help_text="verify_sources tool'undan gelen kaynak dogrulama sonucu.", null=True)),
                ('truth_score', models.FloatField(blank=True, help_text='0.0 (kesin sahte) - 1.0 (kesin dogru) arasinda birlestirilmis dogruluk skoru.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('propagation_graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='graph_engine.propagationgraph')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
