# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysis_ai_analysis_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gnn', 'GNN'), ('bot', 'Bot')], max_length=16)),
                ('source', models.CharField(choices=[('pipeline', 'Analysis Pipeline'), ('agent_tool', 'Agent Tool'), ('legacy_import', 'Legacy Import')], max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('feature_set', models.CharField(blank=True, max_length=255)),
                ('graph_id_snapshot', models.BigIntegerField(blank=True, null=True)),
                ('artifact_ref', models.CharField(blank=True, max_length=500)),
                ('result', models.JSONField(default=dict)),
                ('cross_domain', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='analyses.analysis')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['analysis', 'kind', '-generated_at'], name='analysis_run_lookup')],
            },
        ),
    ]
