# Generated by Django 5.2.17 on 2026-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_analysismodelrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_mode',
            field=models.CharField(choices=[('fast', 'Hizli'), ('deep', 'Derin')], default='fast', max_length=16),
        ),
    ]
